#!/bin/bash

mkdir -p ~/Library/Developer/Xcode/Templates/File\ Templates/MVVM
rm -rf ~/Library/Developer/Xcode/Templates/File\ Templates/MVVM
cp -R ./MVVM ~/Library/Developer/Xcode/Templates/File\ Templates/
echo "########## INSTALLED ##########"

